<a href="https://colab.research.google.com/github/sardornormirzayev/DS/blob/main/vazifalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data3 = [[[1,2,[2,3,4,5],3,[2,2,34],3.4]]]
arr3 = np.array(data3)

<ipython-input-18-a3b120026965>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array(data3)


In [ ]:
arr3.ndim # arr3 ning o'lchami

3

In [ ]:
data4 = [[1,2,4,4],[3,4,5,6]]
arr4 = np.array(data4)

In [ ]:
arr4

array([list([1, 2, 4, 4, 4]), list([3, 4, 5, 6])], dtype=object)

In [ ]:
arr4.shape # massivning qator va ustunlarini qaytaradi

(2, 4)

In [ ]:
arr4.size # massivning elementlarini sanydi

8

In [ ]:
arr5 = np.zeros((2,4)) # elementlari nollardan iborat bolgan 2 ga 4 matritsa yaratadi

In [ ]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((4,4)) # elementlari 1 lardan iborat bolgan 4 ga 4 matritsa yaratadi

In [ ]:
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np
arr = np.array([[1,4,5],[1,3,2],[3,6,7]])
arr

array([[1, 4, 5],
       [1, 3, 2],
       [3, 6, 7]])

In [ ]:
arr.ndim

2

In [ ]:
names = np.array(['hasan','husan','olim','hasan','jobir','olim'])
names

array(['hasan', 'husan', 'olim', 'hasan', 'jobir', 'olim'], dtype='<U5')

In [ ]:
data = np.random.randn(6,4)
data

array([[-1.03409614, -1.13531152, -0.38756889,  0.96258198],
       [ 0.38918369, -0.73913739, -0.62445496,  0.61855816],
       [ 1.20875153, -0.32946968, -0.37001486, -0.11492947],
       [ 2.46082701, -0.16170126,  0.44108679,  0.40723916],
       [ 0.69144113,  1.17812723, -0.20121487,  0.37295524],
       [-0.60272055, -0.09335407, -0.61776878, -1.1320596 ]])

In [ ]:
data1 = data[names == 'hasan']
data1

array([[-1.03409614, -1.13531152, -0.38756889,  0.96258198],
       [ 2.46082701, -0.16170126,  0.44108679,  0.40723916]])

In [ ]:
mask = (names == 'hasan') | (names == 'olim')
data[mask]

array([[-1.03409614, -1.13531152, -0.38756889,  0.96258198],
       [ 1.20875153, -0.32946968, -0.37001486, -0.11492947],
       [ 2.46082701, -0.16170126,  0.44108679,  0.40723916],
       [-0.60272055, -0.09335407, -0.61776878, -1.1320596 ]])

In [ ]:
data

array([[-1.03409614, -1.13531152, -0.38756889,  0.96258198],
       [ 0.38918369, -0.73913739, -0.62445496,  0.61855816],
       [ 1.20875153, -0.32946968, -0.37001486, -0.11492947],
       [ 2.46082701, -0.16170126,  0.44108679,  0.40723916],
       [ 0.69144113,  1.17812723, -0.20121487,  0.37295524],
       [-0.60272055, -0.09335407, -0.61776878, -1.1320596 ]])

In [ ]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.        , 0.96258198],
       [0.38918369, 0.        , 0.        , 0.61855816],
       [1.20875153, 0.        , 0.        , 0.        ],
       [2.46082701, 0.        , 0.44108679, 0.40723916],
       [0.69144113, 1.17812723, 0.        , 0.37295524],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
arr1 = np.arange(10)
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
modul = abs(arr1) # abs massiv elementlarini moduldan chaqadi
modul

array([0.59338584, 1.21512812, 0.14094286, 2.13652182, 0.50137393,
       0.75097513, 0.25134907, 0.75685416, 0.14161131, 1.00075192])

In [ ]:
ildiz = np.sqrt(arr1)
ildiz

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
kvadrat = np.square(arr1)
kvadrat

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
e_darajasi = np.exp(arr1)
e_darajasi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
lagarifm = np.log(2.71828183e+00)
lagarifm

1.0000000005668856

In [ ]:
logarifm_2 = np.log2(64)
logarifm_2

6.0

In [ ]:
lagarifm_10 = np.log10(100000)
lagarifm_10

5.0

In [ ]:
lagarifm = np.log1p(10)  # log1p = log(1+x) ga teng
lagarifm1 = np.log(11)
lagarifm1
lagarifm # Bu yerda lagarifm1 va lagarifm ikkitasini qiymatlari bir xil

2.3978952727983707

In [ ]:
arr2 = np.random.randn(10)
belgi = np.sign(arr2)
belgi

array([-1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr3 = np.array([1.5,1.2,1.4,1.7,1.1])
yaxlitlash = np.ceil(arr3) # yuqoriga yaxlitlash
yaxlitlash

array([2., 2., 2., 2., 2.])

In [ ]:
yaxlitlash = np.floor(arr3) # pastga yaxlitlash
yaxlitlash

array([1., 1., 1., 1., 1.])

In [ ]:
int_yaxlitlash = np.rint(arr3) # rint martematik yaxlitlaydi
int_yaxlitlash

array([2., 1., 1., 2., 1.])

In [ ]:
arr4 = np.random.randn(10)
arr4

array([ 0.5853004 , -0.66714191,  0.36492899,  1.24302435, -1.08478956,
       -0.50819974, -0.66082628, -0.31047032,  0.52707584,  1.90916606])

In [ ]:
qoldiq,butun = np.modf(arr4) # modf bu sonning qoldiq va butun qismlarini ikkita alohida arraylarda qaytaradi

In [ ]:
print(qoldiq)
print(butun)

[ 0.5853004  -0.66714191  0.36492899  0.24302435 -0.08478956 -0.50819974
 -0.66082628 -0.31047032  0.52707584  0.90916606]
[ 0. -0.  0.  1. -1. -0. -0. -0.  0.  1.]


In [ ]:
np.isnan(arr4) # arr4 ni elementlarini isnan yoki yoqligini tekshiryapti

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr4[0] = np.NaN # arr4 massivni 0 - elementini typini NaN ga ozgartiryapti
# NaN (Not a Number)
np.isnan(arr4) # isnan bu yerda raqm borligini tekshiryapti

array([ True, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr5 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
cos = np.cos(arr5)
cos

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [ ]:
cosh = np.cosh(arr5)
cosh

array([[1.54308063e+00, 3.76219569e+00, 1.00676620e+01],
       [2.73082328e+01, 7.42099485e+01, 2.01715636e+02],
       [5.48317035e+02, 1.49047916e+03, 4.05154203e+03]])

In [ ]:
arccos = np.arccos(0)
arccos

1.5707963267948966

In [ ]:
arr6 = np.random.randn(6)
arr7 = np.random.randn(6)
arr6

array([-0.95684318, -1.47471008,  1.39206728, -0.70101315,  0.13492885,
       -0.31179458])

In [ ]:
arr7

array([-0.08493935,  0.38359991, -0.91716614,  1.31008026,  0.50216063,
       -0.93189995])

In [ ]:
add = np.add(arr6,arr7) # add bu arraylarni mos elementlarini qoshadi
add

array([-1.04178253, -1.09111017,  0.47490114,  0.60906711,  0.63708949,
       -1.24369453])

In [ ]:
subtract = np.subtract(arr6,arr7) # subtract bu array mos elementlarini ayiradi
subtract

array([-0.87190383, -1.85831   ,  2.30923342, -2.01109342, -0.36723178,
        0.62010536])

In [ ]:
multi = np.multiply(arr6,arr7) # multiply bu array elementlarini kopaytiradi
multi

array([ 0.08127364, -0.56569866, -1.27675698, -0.9183835 ,  0.06775596,
        0.29056136])

In [ ]:
arr8 = np.array([1,2,3,4,5,6,7,8,9]) # array elementlarini koratilgan darajaga oshiradi
pow = np.power(arr8,2)
pow

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
max1 = np.maximum(arr6,arr7) # maxsimum array mos elementlarini solishtirib maxlarini qaytaradi fmax esa NaN larni hisobga olmaydi
max1

array([-0.08493935,  0.38359991,  1.39206728,  1.31008026,  0.50216063,
       -0.31179458])

In [ ]:
min = np.minimum(arr6,arr7) # minimum bu arraylar mos elementlarini tekshirib minimumlarini qaytaradi fmin esa NaN larni hisobga olmaydi
min

array([-0.95684318, -1.47471008, -0.91716614, -0.70101315,  0.13492885,
       -0.93189995])

In [ ]:
mod = np.mod(arr6,arr7)
mod

array([-0.0225103 ,  0.05968957, -0.442265  ,  0.60906711,  0.13492885,
       -0.31179458])

In [ ]:
# Massivlar
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [ ]:
# Shartlar
con = np.array([True,False,True,True,False])

In [ ]:
# Where
result = np.where(con,yarr,xarr)
result

array([2.1, 1.2, 2.3, 2.4, 1.5])

In [ ]:
guess = np.random.randn(4,4)
guess

array([[ 1.39200441,  1.46470427, -0.06283879, -1.39443911],
       [ 1.69161415, -2.02667149, -0.30597886,  0.67351089],
       [-1.36168337, -0.67937035, -0.60381664,  0.12293003],
       [-0.09512854, -0.48545254,  0.00551096,  0.91563483]])

In [ ]:
change = np.where(guess>0,'a','b')
change

array([['a', 'a', 'b', 'b'],
       ['a', 'b', 'b', 'a'],
       ['b', 'b', 'b', 'a'],
       ['b', 'b', 'a', 'a']], dtype='<U1')

In [ ]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr1*arr2 # arr1 ning elementlarini arr2 ni mos elemetlariga kopaytiradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
arr1+arr2  # arr1 ning elementlarini arr2 ni mos elemetlariga qoshadi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr2 - arr1 #arr1 ning elementlarini arr2 ni mos elemetlariga ayiradi

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
arr2/arr1 # arr1 ning elementlarini arr2 ni mos elemetlariga boladi

<ipython-input-65-e2e60495effe>:1: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [ ]:
arr1 ** 2 # arr1 ning elementlarini darajga kotaradi

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
arr2 ** 0.5 # arr2 ning elementlarini kvadrat ildizdan chiqaradi

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [ ]:
arrr = np.random.randn(5,4)
arrr

array([[ 0.59270671, -0.99479871, -0.55728433,  0.82320406],
       [ 0.8407184 , -0.77430557,  2.67337045,  0.78530054],
       [-0.48925887, -0.7076368 ,  0.75434423,  1.10363617],
       [ 0.3626334 ,  2.02907771,  1.34591957, -0.79962599],
       [ 0.988608  ,  1.12392406, -0.76159153,  1.01795942]])

In [ ]:
arrr.sum() # sum metodi arrr massivning barcha elementlarini yigindisini hisoblaydi
arrr

array([[ 0.59270671, -0.99479871, -0.55728433,  0.82320406],
       [ 0.8407184 , -0.77430557,  2.67337045,  0.78530054],
       [-0.48925887, -0.7076368 ,  0.75434423,  1.10363617],
       [ 0.3626334 ,  2.02907771,  1.34591957, -0.79962599],
       [ 0.988608  ,  1.12392406, -0.76159153,  1.01795942]])

In [ ]:
arrr.sum(axis=1) # massivning qatorlar yigindisini hisoblaydi

array([-0.13617226,  3.52508384,  0.66108473,  2.93800468,  2.36889995])

In [ ]:
np.sum(arrr,axis=0) # massivning ustunlar yigindisini hisoblaydi

array([2.29540764, 0.67626069, 3.4547584 , 2.93047421])

In [ ]:
np.max(arrr) # massivning eng katta elementini qaytaradi
np.min(arrr) # massivning eng kichik elementini qaytaradi

-0.9947987097118863

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.cumsum(arr1) # ketma - ket qoshib boradi

array([ 0,  1,  3,  6, 10, 15])

In [ ]:
# sodda kod
orta = sum(arr)/len(arr)
orta

NameError: ignored

In [ ]:
np.mean(arrr)

0.46784504687137024